### PR TITLE
remove note id, and add parent_id

### LINKED ISSUE #55: Using Duplicate on a Card from Note causes Uncaught Exception
When trying to duplicate a card that was created from a Note, there is an SQL UNIQUE constraint failure.

1. Create a new Kanban board
2. Add a new card to the Backlog stack
3. Use the Create note from card.. function to create the card as a note
4. Try to duplicate the card.

Image

### PR DESCRIPTION
**Pull request by bsavant**
Fixes #55

- Removes id from duplicate copy of note before being saved.
- Adds parent_id from original note to duplicate copy so that it will be created in the same folder

### CODE REVIEW

File: src/messageHandlers.ts [hunk 1]
```diff
@@ -150,6 +150,7 @@ const messageHandlers:Record<IpcMessageType, MessageHandler> = {
 
 		const newNote = {
 			...note,
+			id: '',
 			title: note.title + ' - Copy',
 			tags: tagTitles.join(','),
 		};
```
Comment (laurent22) [inline src/messageHandlers.ts:156]: I'm suggesting delete the ID instead but otherwise looks good. Thanks for fixing this!

```suggestion
		const newNote = {
			...note,
			title: note.title + ' - Copy',
			tags: tagTitles.join(','),
		};
		
		delete newNote.id;
```
